resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: feature/dacpac_infra

pool:
  vmImage: 'windows-latest'

parameters:
  - name: projectNamesConfigurations
    type: object
    default:
      - projectName: 'sqlmoveme'
        environmentName: 'dev2'
        regionAbrvs: ['eus']
        projectExtension: '.sqlproj'
        buildArguments: '/p:NetCoreBuild=true'
        sqlServerName: 'moveme'
        sqlDatabaseName: 'moveme'
        resourceGroupName: sqlserver
        ipDetectionMethod: 'AutoDetect'
        deployType: 'DacpacTask'
        authenticationType: 'servicePrincipal'
  - name: serviceName
    type: string
    default: 'sqlmoveemecicd'
  - name: artifactsToPublish
    type: object
    default: ['security', 'infrastructure']
  - name: deploymentScope
    type: string
    default: 'resourceGroup'
  - name: bicepParamExt
    type: boolean
    default: true



stages:
  - template: stages/dotnet_sql_infra_build_stage.yml@templates
    parameters:
      projectNamesConfigurations: ${{ parameters.projectNamesConfigurations}}
      serviceName: '${{ parameters.serviceName}}'
      artifactsToPublish: ${{ parameters.artifactsToPublish}}
      deploymentScope: ${{ parameters.deploymentScope}}
      bicepParamExt: ${{ parameters.bicepParamExt}}
  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
    - template: stages/dacpac_infra_deploy_stage.yml@templates
      parameters:
        projectConfigurations: ${{ parameters.projectNamesConfigurations }}
        serviceName: ${{ parameters.serviceName }}
        deploymentScope: ${{ parameters.deploymentScope}}
        bicepParamExt: ${{ parameters.bicepParamExt}}