resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: feature/dacpac

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: projectNamesConfigurations
    type: object
    default:
      - projectName: 'sqlmoveme'
        projectExtension: '.sqlproj'
  - name: serviceName
    type: string
    default: 'sqlmoveemecicd'
  - name: artifactsToPublish
    type: object
    default: ['security']


stages:
  - template: stages/msbuild_build_stage.yml@templates
    parameters:
      projectNamesConfigurations: ${{ parameters.projectNamesConfigurations}}
      serviceName: '${{ parameters.serviceName}}'
      artifactsToPublish: ${{ parameters.artifactsToPublish}}