resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: fix/dacpac_deploy_publish

trigger:
  - none

pool:
  vmImage: 'windows-latest'

parameters:
  - name: projectNamesConfigurations
    type: object
    default:
      - projectName: 'sqlmoveme' 
        environmentName: 'dev'
        regionAbrvs: ['cus']
        projectExtension: '.sqlproj'
        buildArguments: '/p:NetCoreBuild=true /p:DacVersion=1.0.1'
        sqlServerName: 'adventureworksentra'
        sqlDatabaseName: 'moveme'
        resourceGroupName: adventureworksentra
        ipDetectionMethod: 'AutoDetect'
        deployType: 'DacpacTask'
        authenticationType: 'servicePrincipal'
        buildConfiguration: 'dev'
        dacpacAdditionalArguments: '/p:DropObjectsNotInSource=true /p:RegisterDataTierApplication=true /p:BlockOnPossibleDataLoss=false'
      - projectName: 'sqlmoveme' 
        environmentName: 'tst'
        regionAbrvs: ['cus']
        projectExtension: '.sqlproj'
        buildArguments: '/p:NetCoreBuild=true /p:DacVersion=1.0'
        sqlServerName: 'adventureworksentra'
        sqlDatabaseName: 'moveme'
        resourceGroupName: adventureworksentra
        ipDetectionMethod: 'AutoDetect'
        deployType: 'DacpacTask'
        authenticationType: 'servicePrincipal'
        buildConfiguration: 'tst'
        dacpacAdditionalArguments: '/p:DropObjectsNotInSource=true /p:RegisterDataTierApplication=true /p:BlockOnPossibleDataLoss=false'
      

  - name: serviceName
    type: string
    default: 'adventureworksentra'

stages:
  - template: stages/dotnet_sql_build_stage.yml@templates
    parameters:
      projectNamesConfigurations: ${{ parameters.projectNamesConfigurations}}
      serviceName: '${{ parameters.serviceName}}'

  - template: stages/dacpac_deploy_stage.yml@templates
    parameters:
      projectConfigurations: ${{ parameters.projectNamesConfigurations }}
      serviceName: ${{ parameters.serviceName }}

