resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth
    ref: feature/dacpac

pool:
  vmImage: 'ubuntu-latest'

parameters:
  - name: projectNamesConfigurations
    type: object
    default:
      - projectName: 'sqlmoveme'
        publishWebProject: false
        dotnetTest: false
        efMigrationScript: false
        startUpProjectName: ''
  - name: serviceName
    type: string
    default: 'slqmovemecicd'
  - name: zipAfterPublish
    type: boolean
    default: false
  - name: artifactsToPublish
    type: object
    default: ['security']


stages:
  - template: stages/dacpac_build_stage.yml@templates
    parameters:
      projectNamesConfigurations: ${{ parameters.projectNamesConfigurations}}
      serviceName: '${{ parameters.serviceName}}'
      zipAfterPublish: ${{ parameters.zipAfterPublish}}
      artifactsToPublish: ${{ parameters.artifactsToPublish}}