resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth

trigger:
  - none

pool:
  vmImage: 'windows-latest'

parameters:
  - name: projectNamesConfigurations
    type: object
    default:
      - projectName: 'sqlmoveme'
        environmentName: 'dev'
        regionAbrvs: ['cus']
        projectExtension: '.sqlproj'
        buildArguments: '/p:NetCoreBuild=true'
        sqlServerName: 'adventureworksentra'
        sqlDatabaseName: 'moveme'
        resourceGroupName: adventureworksentra
        ipDetectionMethod: 'AutoDetect'
        deployType: 'DacpacTask'
        authenticationType: 'servicePrincipal'
        projectConfiguration: 'Release'
  - name: serviceName
    type: string
    default: 'adventureworksentra'
  - name: artifactsToPublish
    type: object
    default: ['security', 'infrastructure']
  - name: deploymentScope
    type: string
    default: 'resourceGroup'
  - name: bicepParamExt
    type: boolean
    default: true
stages:
- stage: bicepaadentra_build
  jobs:
  - job: build_publish_sql_sqlmoveme_dev
    steps:
    - task: UseDotNet@2
      displayName: Use .NET SDK v3.1.x
      inputs:
        packageType: 'sdk'
        version: 3.1.x
        includePreviewVersions: true
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: build
        projects: $(Build.SourcesDirectory)/src/sqlmoveme/*.sqlproj
        arguments: --configuration dev /p:NetCoreBuild=true
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact sqlmoveme_dev_dev '
      inputs:
        targetPath: $(Build.SourcesDirectory)/src/sqlmoveme/bin/dev
        artifact: sqlmoveme_dev_dev
        properties: ''
  - job: build_publish_sql_sqlmoveme_tst
    steps:
    - task: UseDotNet@2
      displayName: Use .NET SDK v3.1.x
      inputs:
        packageType: 'sdk'
        version: 3.1.x
        includePreviewVersions: true
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: build
        projects: $(Build.SourcesDirectory)/src/sqlmoveme/*.sqlproj
        arguments: --configuration tst /p:NetCoreBuild=true
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact sqlmoveme_tst_tst '
      inputs:
        targetPath: $(Build.SourcesDirectory)/src/sqlmoveme/bin/tst
        artifact: sqlmoveme_tst_tst
        properties: ''
stages:
  - template: stages/dotnet_sql_build_stage.yml@templates
    parameters:
      projectNamesConfigurations: ${{ parameters.projectNamesConfigurations}}
      serviceName: '${{ parameters.serviceName}}'
      artifactsToPublish: ${{ parameters.artifactsToPublish}}

  - ${{ if eq(variables['Build.SourceBranch'], 'refs/heads/main')}}:
    - template: stages/dacpac_infra_deploy_stage.yml@templates
      parameters:
        projectConfigurations: ${{ parameters.projectNamesConfigurations }}
        serviceName: ${{ parameters.serviceName }}

