resources:
  repositories:
  - repository: templates
    type: github
    name: JFolberth/TheYAMLPipelineOne
    endpoint: JFolberth

trigger:
  - none

pool:
  vmImage: 'windows-latest'

parameters:
  - name: projectNamesConfigurations
    type: object
    default:
      - environmentName: 'dev' 
        projectName: 'sqlmoveme'
        regionAbrvs: ['cus']
        projectExtension: '.sqlproj'
        buildArguments: '/p:NetCoreBuild=true'
        sqlServerName: 'adventureworksentra'
        sqlDatabaseName: 'moveme'
        resourceGroupName: adventureworksentra
        ipDetectionMethod: 'AutoDetect'
        deployType: 'DacpacTask'
        authenticationType: 'servicePrincipal'
        projectConfiguration: 'dev'
      - environmentName: 'tst'
        projectName: 'sqlmoveme'
        regionAbrvs: ['cus']
        projectExtension: '.sqlproj'
        buildArguments: '/p:NetCoreBuild=true'
        sqlServerName: 'adventureworksentra'
        sqlDatabaseName: 'moveme'
        ipDetectionMethod: 'AutoDetect'
        deployType: 'DacpacTask'
        authenticationType: 'servicePrincipal'
        projectConfiguration: 'tst'
  - name: serviceName
    type: string
    default: 'adventureworksentra'

stages:
  - template: stages/dotnet_sql_build_stage.yml@templates
    parameters:
      projectNamesConfigurations: ${{ parameters.projectNamesConfigurations}}
      serviceName: '${{ parameters.serviceName}}'

  - template: stages/dacpac_deploy_stage.yml@templates
    parameters:
      projectConfigurations: ${{ parameters.projectNamesConfigurations }}
      serviceName: ${{ parameters.serviceName }}

