trigger:
  none

pool:
  vmImage: 'windows-latest'
stages:
- stage: bicepaadentra_build
  jobs:
  - job: build_publish_sql_sqlmoveme
    steps:
    - task: UseDotNet@2
      displayName: Use .NET SDK v3.1.x
      inputs:
        packageType: 'sdk'
        version: 3.1.x
        includePreviewVersions: true
    - task: DotNetCoreCLI@2
      displayName: dotnet build
      inputs:
        command: build
        projects: $(Build.SourcesDirectory)/src/sqlmoveme/*.sqlproj
        arguments: --configuration dev /p:NetCoreBuild=true
    - task: PublishPipelineArtifact@1
      displayName: 'Publish Pipeline Artifact sqlmoveme_dev_dev '
      inputs:
        targetPath: $(Build.SourcesDirectory)/src/sqlmoveme/bin/dev
        artifact: sqlmoveme_dev_dev
        properties: ''
- stage: sqlmoveemecicd_dev_cus_dacpac_deploy
  jobs:
  - deployment: sqlmoveemecicd_app_dev_cus
    environment:
      name: dev2
    dependsOn: []
   
    strategy:
      runOnce:
        deploy:
          steps:
          - task: SqlAzureDacpacDeployment@1
            displayName: Publish sqlmoveme on sql-adventureworksentra-dev-cus.database.windows.net
            inputs:
              DeploymentAction: Publish
              azureSubscription: AzureDevExtServiceConnection
              AuthenticationType: servicePrincipal
              ServerName: sql-adventureworksentra-dev-cus.database.windows.net
              DatabaseName: sqlmoveme
              deployType: DacpacTask
              DacpacFile: $(Agent.BuildDirectory)\sqlmoveme_dev_dev\**\*.dacpac
              AdditionalArguments: ''
              DeleteFirewallRule: True
